server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Increase upload limit for batch document upload.
  client_max_body_size 200m;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
